
int BT_COMMAND_FORWARD_CODES[] = {'1'};
int BT_COMMAND_FORWARD_LEFT_CODES[] = {'2'};
int BT_COMMAND_FORWARD_RIGHT_CODES[] = {'3'};

int BT_COMMAND_BACKWARD_CODES[] = {'4'};
int BT_COMMAND_BACKWARD_LEFT_CODES[] = {'5'};
int BT_COMMAND_BACKWARD_RIGHT_CODES[] = {'6'};


int BT_COMMAND_TURN_LEFT_CODES[] = {'7'};
int BT_COMMAND_TURN_RIGHT_CODES[] = {'8'};


int BT_COMMAND_STOP_CODES[] = {'9'};
int BT_COMMAND_VERY_SLOW_CODES[] = {'a'};
int BT_COMMAND_SLOW_CODES[] = {'b'};
int BT_COMMAND_FAST_CODES[] = {'c'};
int BT_COMMAND_VERY_FAST_CODES[] = {'d'};
