
int IR_COMMAND_FORWARD_CODES[] = {'1'};
int IR_COMMAND_FORWARD_LEFT_CODES[] = {'2'};
int IR_COMMAND_FORWARD_RIGHT_CODES[] = {'3'};

int IR_COMMAND_BACKWARD_CODES[] = {'4'};
int IR_COMMAND_BACKWARD_LEFT_CODES[] = {'5'};
int IR_COMMAND_BACKWARD_RIGHT_CODES[] = {'6'};


int IR_COMMAND_TURN_LEFT_CODES[] = {'7'};
int IR_COMMAND_TURN_RIGHT_CODES[] = {'8'};


int IR_COMMAND_STOP_CODES[] = {'9'};
int IR_COMMAND_VERY_SLOW_CODES[] = {'a'};
int IR_COMMAND_SLOW_CODES[] = {'b'};
int IR_COMMAND_FAST_CODES[] = {'c'};
int IR_COMMAND_VERY_FAST_CODES[] = {'d'};
